### ISSUE TITLE
Toot plugin vulnerable to shell injection

### ISSUE THREAD

**Issue by jmdejong** [archangelic/pinhook-tilde#4]
Because the toot plugin uses string interpolation with user input to generate a shell statement, it is possible to inject shell code to let pinhook execute arbitrary code with your file permissions.
Example:

    !toot `/tmp/evil_script`

The correct solution is to use subprocess.call (or subprocess.run) with a list as first argument (instead of a string)

**Comment by archangelic** [comment]
This is now fixed alongside the lockup when no argument is passed!
