### ISSUE TITLE
!ttv command for tildetv

### ISSUE THREAD

**Issue by resir014** [archangelic/pinhook-tilde#5]
I would create this myself, but I can't Python, so I'll make this up for grabs for anyone.

As a user I'd like to have a `!ttv` command so that I could list all videos currently featured in [tildetv](https://tilde.town/~resir014/tildetv/). A JSON datadump is available [here](https://tilde.town/~karlen/tv/videos.json) and the tildetv web interface currently pulls from it.

**Comment by themushmouth** [comment]
I definitely think this is good. it'll bring more traffic to tildetv and help us not have to go into a command line away from irc.

**Comment by archangelic** [comment]
I have a tildetvbot on the town (~archangelic/tildetvbot/) it’s just that for some reason my auto script doesn’t restart it.

**Comment by archangelic** [comment]
tbh, i can put the code into a pinhook plugin for sure. it looks like tildetvbot is a pre-pinhook bot with some issues.
